# Generated by Django 4.2.3 on 2023-10-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documento',
            field=models.CharField(max_length=20, unique=True, verbose_name='Documento'),
        ),
    ]
